### ISSUE TITLE
some question without code （代码无关的小问题）

### ISSUE THREAD

**Issue by wusopp** [ImSjt/RtspServer#1]
请教几个小问题
1、该RtspServer 能支持几路输出呢，延时情况怎么样呢？
2、代码遵循什么协议呢？是否可以商用

**Comment by ImSjt** [comment]
你好
1、该RtspServer支持几路流理论上没有限制，主要取决于处理器性能。延迟情况我并没有进行详细测试
2、该项目代码完全开源，但并不建议商用，此项目主要目的是用于学习Rtsp协议。如果想要商用，如果是做IPCamera的话建议采用live555，如果做转发服务器的话可以看一下EasyDarwin
---原始邮件---
发件人:"xuhe018"<notifications@github.com>
发送时间:2019年8月15日 星期四 上午8:20
收件人:"ImSjt/RtspServer"<RtspServer@noreply.github.com>
抄送:"Subscribed"<subscribed@noreply.github.com>
主题:[ImSjt/RtspServer] some question without code （代码无关的小问题） (#1)

请教几个小问题
1、该RtspServer 能支持几路输出呢，延时情况怎么样呢？
2、代码遵循什么协议呢？是否可以商用

&mdash;
